# The blog source is in the site branch
# so we want to only build when a push has been made to that branch
branches:
  only:
  - site
git:
  depth: false

# This gives us full control over what we intend to do
# in the job
language: generic
# Needed for docker
sudo: required
services:
  - docker

# Specify the github pages deploy provider
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: site
  target_branch: master
  local_dir: ${TRAVIS_BUILD_DIR}/output
  fqdn: echorand.me # This updates the repository settings in GitHub and also adds a CNAME file in the master branch
before_install:
  - docker build -t amitsaha/pelican  .
install:
  - docker run -v `pwd`:/site:Z -t amitsaha/pelican
